### PR TITLE
Sonya/search param

### PR DESCRIPTION
**Pull request by sonyakim-dev**
- when an item is selected from a dropdown list, updates url param `/?term=[term]`
  image
- create card loading component
  Screenshot 2024-02-15 at 12 54 08 AM
- automatically open window when yarn started

### CODE REVIEW

**Comment by awllms** [comment]
Looks good to me!

**Comment by rainawan** [comment]
lgtm!

**Comment by awllms** [comment]
Can we limit the scope of our PRs in the future? This PR is changing how we handle data within our app again when it should only be the search param feature. We should still merge this, but I think we should limit the scope of our features in the future and only work on our dedicated features or slim them down to move faster and not deal with so many merge conflicts. If a person wants to take over a feature, that is okay, but two people working on the same feature will cause more issues than needed for what we are doing, especially if we are not letting each other know about the changes we are making. Thanks! 🙂

**Comment by sonyakim-dev** [comment]
@awllms I was thinking about how we can reuse the data fetching function across the website by passing all the different filtering conditions, and I noticed this changes are not good so I decided to completely change the function. I was trying to make those changes on the next pr, but I will just push changes on this pr so you can review it.

**Comment by sonyakim-dev** [comment]
@awllms I pushed the changes. Would you be able to review it please? I made `getEntriesQuery()` and `getTermssQuery()` that we can use for not only searching but also other filtering/nonfiltering cases

**Comment by sonyakim-dev** [comment]
@awllms Are you working on fetching data? I thought you are working on the adding posts. I was thinking about how we can reuse the data fetching function across the website by passing all the different filtering conditions, and I noticed the changes are not good so I decided to completely change the function. Then I will revert the fetch functions and make another pr for the fetching function change.

**Pull request merged**
