### PR TITLE
Sonya/search bar

### PR DESCRIPTION
**Pull request by sonyakim-dev**
image
- create a search bar and autocomplete
- style navbar

### CODE REVIEW

**Comment by awllms** [comment]
For some reason I can't run this branch locally. I'm having an issue with Navbar.
Screenshot 2024-02-10 at 9 39 54 AM

I have the Navbar loaded. Did you get this error?

**Comment by sonyakim-dev** [comment]
@awllms oh, this is because i changed the filename 'Navbar' to 'NavBar' but git doesn't distinguish this change.. I changed it because the name was conflicting with nextui's Navbar component. I will fix it

**Comment by awllms** [comment]
I see the update, but I'm getting the same error but now for the component SearchBar. 😆

**Comment by awllms** [comment]
All ready to merge! Looking good!

**Pull request merged**
